import Head from "next/head";
import { SignOutButton, useAuth } from "@clerk/nextjs";
import { SignIn, UserButton, useUser } from "@clerk/clerk-react";

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const {isSignedIn, user } = useUser();
  if (!isLoaded || !userId) {
    return (<>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          hello you don't have an account
        </div>
        <SignIn/>
      </main>
    </>);
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          Hello, {userId} your current active session is {sessionId}
        </div>
        <UserButton afterSignOutUrl="/"/>
      </main>
    </>
  );
}
