import Head from "next/head";
import { SignOutButton, useAuth } from "@clerk/nextjs";
import { SignIn, UserButton, useUser } from "@clerk/clerk-react";
import { useState } from "react";

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const {user } = useUser();

  const [isModalOpen, setModalOpen] = useState(false);

  const toggleModal = () => {
    setModalOpen(!isModalOpen);
  };
  if (!isLoaded || !userId) {
    return (<>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div>
          hello you do not have an account
        </div>
              <button
                className="fixed top-4 right-4 bg-blue-700 hover:bg-blue-900 text-white py-2 px-4 rounded"
                onClick={toggleModal}
              >
                Open Modal
              </button>

              {isModalOpen && (
              <div className="fixed inset-0 flex items-center justify-center z-50 backdrop-blur-md">
                <div className="modal-bg fixed inset-0 opacity-50"></div>
                <div className="modal-content bg-transparent p-8 rounded z-50 flex flex-col">
                  <SignIn />
                  <button
                    className="mt-4 mr-7 bg-blue-700 hover:bg-blue-900 text-white py-2 px-4 rounded self-end"
                    onClick={toggleModal}
                  >
                    Close Modal
                  </button>
                </div>
              </div>
            )}
        
        
      </main>
    </>);
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          Hello, {user?.username} your current active session is {sessionId}
        </div>
        <UserButton afterSignOutUrl="/"/>
      </main>
    </>
  );
}
